config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

    resources :orders

    namespace :admin do
      resources :orders
    end

    resources :products do
      member do
        post :buy
        post :cancel
       end
    end
    resources :users

    resources :events do
      resources :comments, :controller => 'event_comments'
      resources :likes
      resources :types, :controller => 'event_types'
    end

      get 'index' => 'abouts#index'
      get 'about' => 'abouts#about'

     root 'abouts#index'

end

app/models/event.rb
class Event < ActiveRecord::Base

  validates_presence_of :topic

  belongs_to :category

  belongs_to :type

  belongs_to :user

  has_many :comments

  has_many :likes
  has_many :like_users, :through => :likes, :source => :user


  delegate :name, :to => :category, :prefix => true, :allow_nil => true
  delegate :name, :to => :type, :prefix => true, :allow_nil => true

  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\Z/

  def finy_like_by(user)
    user && self.likes.find_by_user_id( user.id )
  end


end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :authenticate_user!, :except => [:index]

  before_action :set_event, :only => [ :show, :edit, :update, :destroy]

  def about
  end

  def index

   @events = Event.page(params[:page]).per(8)

   @events = @events.where(category_id: params[:category_id]) if params[:category_id]
   @events = @events.where(type_id: params[:type_id]) if params[:type_id]

   @categories = Category.all
   @types = Type.all

       if params[:sort] == "created_at DESC"
        @events = @events.order("created_at DESC")
       elsif params[:sort] == "created_at"
        @events = @events.order("created_at ")

       elsif params[:sort] == "type_id"
        @events = @events.order("type_id")
       elsif params[:sort] == "type_id DESC"
        @events = @events.order("type_id DESC")

       elsif params[:sort] == "category_id"
        @events = @events.order("category_id")
       elsif params[:sort] == "category_id DESC"
        @events = @events.order("category_id DESC")

       elsif params[:sort] == "topic"
        @events = @events.order("topic")
       elsif params[:sort] == "topic DESC"
        @events = @events.order("topic DESC")

       elsif params[:sort] == "user_id"
        @events = @events.order("user_id")
       elsif params[:sort] == "user_id DESC"
        @events = @events.order("user_id DESC")

       elsif params[:sort] == "comments_count"
        @events = @events.order("comments_count")
       elsif params[:sort] == "comments_count DESC"
        @events = @events.order("comments_count DESC")

       elsif params[:sort] == "likes_count"
        @events = @events.order("likes_count")
       elsif params[:sort] == "likes_count DESC"
        @events = @events.order("likes_count DESC")

       elsif params[:sort] == "comments_created_at"
        @events = @events.order("comments_created_at")
       else params[:sort] == "comments_created_at DESC"
        @events = @events.order("comments_created_at DESC")

        end

  end

  def show
  @page_title = @event.topic
  @comment = Comment.new
  @comments = @event.comments
  @likes = @event.likes
  end

  def new
    @event = Event.new
  end

  def create

    @event = Event.new(event_params)

    @event.user = current_user

      if @event.save
        flash[:alert] = "建立成功"
        redirect_to events_url

      else
        render :action => :new
        flash[:alert] = "請輸入標題"
      end
  end

    def update


      if params[:_remove_logo] == "1"
        @event.logo = nil
      end

      if @event.update(event_params)
        redirect_to :action => :show, :id => @event
        flash[:notice] = "修改成功"
      else
        render :action => :edit
        flash[:alert] = "請輸入標題"
      end
    end

  def edit
  end

  def destroy
    @event = current_user.events.find( params[:id] )
    @event.destroy
    redirect_to :back

    flash[:alert] = "刪除成功"
  end

private

def event_params
  params.require(:event).permit(:topic, :description, :article, :category_id, :logo, :type_id)
end

def set_event
  @event = Event.find(params[:id])
end

end

app/helpers/events_helper.rb
module EventsHelper
  def display_comments_created_at_time(event)
    if event.comments_created_at
      event_time = event.comments_created_at.strftime('%F') + " " + event.comments_created_at.strftime('%R')
    else
      "目前沒人留言"
    end
  end
end

app/views/events/_comment_count.html.erb
<font size="4">留言(  <%= @event.comments.count %> ) :</font>

app/views/events/_event.html.erb
<div class="masonryitem">

    <div class="thumbnail">
        <img src="http://placehold.it/320x150" alt="">
        <div class="caption">
            <h4 class="pull-right"> <%= event.user.first_name %> </h4>
            <h4> <%=link_to event.topic, event_path(event) %></a>
            </h4>
            <p>See more snippets like this online store item at</p>
        </div>


        <div class="ratings">
        <p class="pull-right"><%= event.comments.count %> comments</p>
        <p>
        <%= event.likes.count %>
        <% if current_user && event.user == current_user %>
        <%= link_to '修改', edit_event_path(event) %>
        <%= link_to '刪除', event_path(event),:method => :delete  %>
        <% end %>
        </p>

        </div>
    </div>
</div>

app/views/events/_form.html.erb
<h1> <%= f.label :topic, "標題: "%> </h1>
<%= f.text_field :topic %>

<%= f.label :category_id, "種類: "%>
<%= f.select :category_id, Category.all.map{|x| [x.name, x.id]} %>

<%= f.label :type_id, "車種: "%>
<%= f.select :type_id, Type.all.map{ |t| [t.name, t.id] } %>

<%= f.cktext_area :article, :class => 'someclass', :ckeditor => {:language => 'zh-tw'} %>

app/views/events/_like.html.erb
<font size="5"> 馬力值: <%= @event.likes.count %> hp </font>

<% if like %>
<%= link_to " -1 hp", event_like_path(@event, like),:remote => true, :method => :delete, :class => "btn btn-danger btn-lg" %>
<% else %>
<%= link_to " +1 hp", event_likes_path(@event),:remote => true, :method => :post, :class => "btn btn-primary btn-lg" %>
<% end %>

app/views/events/about.html.erb
<h1>這是aobut</h1>

app/views/events/comment_count.js.erb
$("#comments_count").html("<font size="4">留言(  <%= @event.comments.count %> ):</font>")

app/views/events/edit.html.erb
<head>

    <script src="/ckeditor/ckeditor.js"></script>
</head>

<body class = "container">
  <% if @event.logo.exists? %>
    <%= image_tag ( @event.logo.url) %>
  <% else %>
     None
  <% end %>
<%= form_for @event, :url =>event_path(@event), :method => :patch do |f| %>
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= f.submit "Update" %>
<% end %>

  <p><%= link_to '回到首頁', events_path %></p>
</body>

app/views/events/index.html.erb
</style>
 <script type="text/javascript">
$(function(){
var $container = $('#container');
$container.imagesLoaded(function(){
$container.masonry({
itemSelector : '.item',
columnWidth : 240
});
});
});
</script>



<body bgcolor="#000000">
    <!-- Page Content -->
    <div class="container">

        <!-- Jumbotron Header -->
        <header>
         <div class = "row header_info">
           <div class="col-lg-6">
             <div class = "info">
                <font color="#FFFFFF"><h1 >歡迎! FZR STUDIO</h1></font>
                <br></br>
                <font color="#FFFFFF"><p>1989年台灣山葉參考國外XV250 V型雙缸引擎原型為藍本，</p></font><font color="#FFFFFF"><p>外型參考FZR250，打造一台小型化仿賽車。</p></font>
                <font color="#FFFFFF"><p>採用了前雙碟,後單碟式煞車，中置多連桿避震器，</p></font><font color="#FFFFFF"><p>車重144KG，在彎道及高速行駛時都有極佳的穩定性,</p></font><font color="#FFFFFF"><p>超過當時市面上任何一款打檔摩托車。
                </p></font>
                <br></br>
                <p><a class="btn btn-primary btn-large">關於本站</a></p>
              </div>
           </div>
            <div class="col-lg-6">
              <div class="row carousel-holder ">

                        <div class="col-md-12">
                            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                                <ol class="carousel-indicators">
                                    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                                    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                                    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                                </ol>
                                <div class="carousel-inner">
                                    <div class="item active">
                                        <div class="slide-image">
                                        <%= image_tag("slide_image1.png", :size => "500x334") %>
                                        </div>
                                    </div>
                                    <div class="item">
                                        <div class="slide-image">
                                        <%= image_tag("slide_image2.png", :size => "500x334") %>
                                        </div>
                                    </div>
                                    <div class="item">
                                        <div class="slide-image">
                                        <%= image_tag("slide_image3.png", :size => "500x334") %>
                                        </div>
                                    </div>
                                </div>
                                <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                                    <span class="glyphicon glyphicon-chevron-left"></span>
                                </a>
                                <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                                    <span class="glyphicon glyphicon-chevron-right"></span>
                                </a>
                            </div>
                        </div>

             </div>


           </div>
          </div>
        </header>

        <hr>

        <!-- Title -->
        <div class="row">
            <div class="col-lg-12">
                <h3></h3>
            </div>
        </div>
         <div class="container">

        <div class="row">

            <div class="col-sm-2 col-md-2 col-lg-2">
                <div class="list-group">
                    <button class="list-group-item">
                    <%= link_to "所有文章", events_path%>
                    </button>
                    <% @categories.each do |category| %>
                    <button class="list-group-item">
                    <a><%= link_to category.name , "/events?category_id=#{category.id}" %></a>
                    </button>
                    <% end %>
                </div>
            </div>

            <div class="col-sm-10 col-md-10 col-lg-10">
               <div class="row selectbar">
          <td width="100" align="center" valign = "middle">
          類別
          <%= link_to events_path( :type_id => params[:type_id] , :category_id => params[:category_id] ,:sort => "category_id") do%>
          <i class="glyphicon glyphicon-triangle-top"></i>
          <% end %>
          <%= link_to  events_path( :type_id => params[:type_id] ,  :category_id => params[:category_id] ,:sort => "category_id DESC") do%>
          <i class="glyphicon glyphicon-triangle-bottom"></i>
          <% end %>
          </td>
          <td width="100" align="center" valign = "middle">
          車種
          <%= link_to  events_path( :type_id => params[:type_id] ,  :category_id => params[:category_id] ,:sort => "type_id") do%>
          <i class="glyphicon glyphicon-triangle-top"></i>
          <% end %>
          <%= link_to  events_path( :type_id => params[:type_id] ,  :category_id => params[:category_id] ,:sort => "type_id DESC") do%>
          <i class="glyphicon glyphicon-triangle-bottom"></i>
          <% end %>
          </td>
          <td width="240" align="center" valign = "middle">
          標題
          <%= link_to  events_path( :type_id => params[:type_id] ,  :category_id => params[:category_id] ,:sort => "topic") do%>
          <i class="glyphicon glyphicon-triangle-top"></i>
          <% end %>
          <%= link_to  events_path( :type_id => params[:type_id] ,  :category_id => params[:category_id] , :sort => "topic DESC") do%>
          <i class="glyphicon glyphicon-triangle-bottom"></i>
          <% end %>
          </td>
          <td width="120" align="center" valign = "middle">
          使用者
          <%= link_to  events_path( :type_id => params[:type_id] ,  :category_id => params[:category_id] , :sort => "user_id")  do%>
          <i class="glyphicon glyphicon-triangle-top"></i>
          <% end %>
          <%= link_to  events_path( :type_id => params[:type_id] ,  :category_id => params[:category_id] , :sort => "user_id DESC") do%>
          <i class="glyphicon glyphicon-triangle-bottom"></i>
          <% end %>
          </td>
          <td width="120" align="center" valign = "middle">
          留言數
          <%= link_to  events_path( :type_id => params[:type_id] ,  :category_id => params[:category_id] , :sort => "comments_count") do%>
          <i class="glyphicon glyphicon-triangle-top"></i>
          <% end %>
          <%= link_to  events_path( :type_id => params[:type_id] ,  :category_id => params[:category_id] , :sort => "comments_count DESC") do%>
          <i class="glyphicon glyphicon-triangle-bottom"></i>
          <% end %>
          </td>
          <td width="120" align="center" valign = "middle">
          馬力值
          <%= link_to  events_path( :type_id => params[:type_id] ,  :category_id => params[:category_id] , :sort => "likes_count") do%>
          <i class="glyphicon glyphicon-triangle-top"></i>
          <% end %>
          <%= link_to  events_path( :type_id => params[:type_id] ,  :category_id => params[:category_id] , :sort => "likes_count DESC") do%>
          <i class="glyphicon glyphicon-triangle-bottom"></i>
          <% end %>
          </td>
          <td width="180" align="center" valign = "middle">
          發文時間
          <%= link_to  events_path( :type_id => params[:type_id] ,  :category_id => params[:category_id] , :sort => "created_at") do%>
          <i class="glyphicon glyphicon-triangle-top"></i>
          <% end %>
          <%= link_to  events_path( :type_id => params[:type_id] ,  :category_id => params[:category_id] , :sort => "created_at DESC") do%>
          <i class="glyphicon glyphicon-triangle-bottom"></i>
          <% end %>
          </td>
          <td width="180" align="center" valign = "middle">
          最後留言
          <%= link_to  events_path( :type_id => params[:type_id] ,  :category_id => params[:category_id] , :sort => "comments_created_at") do%>
          <i class="glyphicon glyphicon-triangle-top"></i>
          <% end %>
          <%= link_to  events_path( :type_id => params[:type_id] ,  :category_id => params[:category_id] , :sort => "comments_created_at DESC") do%>
          <i class="glyphicon glyphicon-triangle-bottom"></i>
          <% end %>
          </td>
               </div>
<!-- 這邊以下就是瀑布啦 -->
                <div class="row">

                  <div id="events" >
                   <%= render @events %>
                  </div>

                </div>

                <div id="paginator">
                <%= paginate @events, :remote => true %>
                </div>

            </div>
        </div>

    </div>

    <%= link_to '新增文章', new_event_path, :class => " btn btn-primary active "%>
</body>

app/views/events/index.js.erb
$('#events').html('<%= escape_javascript render(@events) %>');
$('#paginator').html('<%= escape_javascript(paginate(@events, :remote => true).to_s) %>');

app/views/events/like.js.erb
$("#like-area").html("<%= j render( :partial => "events/like", :locals => { :like => @like } ) %>")

app/views/events/new.html.erb
<head>

    <script src="/ckeditor/ckeditor.js"></script>
</head>


<body class = "container">

<% if @event.errors.any? %>
    <% @event.errors.full_messages.each do |m| %>
    <p><%= m %></p>
    <% end %>
 <% end %>

<%= form_for @event, :url => events_path do |f| %>
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= f.submit "Create" %>
<% end %>

  <p><%= link_to '回到首頁', events_path %></p>
</body>

app/views/events/show.html.erb
<body class = "container">

    <div class="container">

        <div class="row">
            <div class="col-lg-8">
                <font size="7"><%= @event.topic %></font>

                <!-- Author -->
                <div class="lead">
                    by <%= @event.user.first_name  %>

                  <% like = @event.finy_like_by(current_user) %>

                  <div id="like-area">
                  <%= render :partial => "like", :locals => { :like => like } %>
                  </div>

                </div>

                <hr>
                <b><span class="glyphicon glyphicon-time"></span>
                <%= @event.created_at.strftime('%F') + " " +@event.created_at.strftime('%R') %>
                </b>
                  <b> #<%= @event.type.try(:name) %><b>
                  <b> #<%= @event.category_name  %></b>
                <hr>
                <%= simple_format(@event.article) %>
                <hr>
                      <div class="well">
                        <div id= "comments_count">
                          <font size="4">留言(  <%= @event.comments.count %> ):</font>
                        </div>

                        <%= form_for @comment, :url => event_comments_path(@event), :class => "form-group", :remote => true do |f| %>
                        <%= f.text_area :comment, rows: 3, class: "form-control" %>
                        <%= f.submit "submit" , :class => "btn btn-primary" %>
                        <% end %>
                      </div>

                      <hr>

                      <ul id="comments-list">
                      <% @comments.each do |comment| %>
                      <%= render :partial => "event_comments/comment", :locals => { :comment => comment } %>
                      <% end %>
                      </ul>

                      </div>

            <!-- Blog Sidebar Widgets Column -->
            <div class="col-md-4">

                <!-- Blog Search Well -->
                <div class="well">
                    <h4>Blog Search</h4>
                    <div class="input-group">
                        <input type="text" class="form-control">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <span class="glyphicon glyphicon-search"></span>
                        </button>
                        </span>
                    </div>
                    <!-- /.input-group -->
                </div>

                <!-- Blog Categories Well -->
                <div class="well">
                    <h4>Blog Categories</h4>
                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="well">
                    <h4>Side Widget Well</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
                </div>

            </div>

        </div>
        <hr>


    </div>

</body>