config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

    resources :orders

    namespace :admin do
      resources :orders
    end

    resources :products do
      member do
        post :buy
        post :cancel
       end
    end
    resources :users

    resources :events do
      resources :comments, :controller => 'event_comments'
      resources :likes
      resources :types, :controller => 'event_types'
    end

      get 'index' => 'abouts#index'
      get 'about' => 'abouts#about'

     root 'abouts#index'

end

app/controllers/event_comments_controller.rb
class EventCommentsController < ApplicationController
    before_action :find_event
    before_action :authenticate_user!

  def index
    @comments = @event.comments
  end

  def show
    @comment = @event.comments.find( params[:id] )
  end

  def new
    @comment = Comment.new
    # @comment = @event.comments.build
  end

  def create
    @comment = @event.comments.create( comment_params )
    @event.comments_created_at  = @comment.created_at
    @comment.user = current_user

    if @comment.save
      @event.save

      respond_to do |format|
      format.html { redirect_to event_path(@event) }
      format.js # create.js.erb
      end

    else
      flash[:alert] = "請輸入內容"
      redirect_to event_path( @event )
    end
  end

  def edit
    @comment = @event.comments.find( params[:id] )
  end

  def update
    @comment = @event.comments.find( params[:id] )

    if @comment.update( comment_params )
      redirect_to event_path( @event )
    else
      render :action => :edit
    end

  end

  def destroy

    @comment = current_user.comments.find( params[:id] )
    @comment.destroy

       respond_to do |format|
       format.html { redirect_to :back }
       format.js # destroy.js.erb
     end
  end

  protected

  def find_event
    @event = Event.find( params[:event_id] )
  end

  def comment_params
    params.require(:comment).permit(:comment)
  end
  def event_params
    params.require(:event).permit(:comments_created_at)
  end

end

app/helpers/event_comments_helper.rb
module EventCommentsHelper
end

app/views/event_comments/_comment.html.erb
<div id="comment-<%= comment.id %>">

      <font size="6"> <%= comment.user.try(:first_name) %> </font>

      <%= comment.created_at.strftime('%F') + " " + comment.created_at.strftime('%R') %>

      <% if current_user && comment.user == current_user %>
         <%= link_to 'edit', edit_event_comment_path(@event, comment) %>
         <%= link_to "Delete", event_comment_path(@event, comment), :method => :delete, :remote => true %>
       <% end %>

      <p><font size="4"><%= comment.comment%></p></font>
 </div>

app/views/event_comments/create.js.erb
$("#comments-list").prepend("<%=j render( :partial => "comment", :locals => { :comment => @comment }  ) %>");
$("#new_comment").trigger('reset');
$("#comments_count").html("<font size='4'>留言(  <%= @event.comments.count %> ):</font>");

app/views/event_comments/destroy.js.erb
$("#comment-<%= @comment.id %>").remove();
$("#comments_count").html("<font size='4'>留言(  <%= @event.comments.count %> ):</font>");

app/views/event_comments/edit.html.erb
<body class = "container">
<%= form_for @comment, :url => event_comment_path(@event, @comment), :html => { :method => :patch } do |f| %>
   <%= f.text_field :comment %>
   <%= f.submit %>
<% end %>
</body>

app/views/event_comments/index.html.erb
<ul>
<% @comments.each do |comment| %>
  <li>
    <%= comment.comment %>
    <%= link_to 'show', event_comment_path(@event, comment) %>
    <%= link_to 'edit', edit_event_comment_path(@event, comment) %>
    <%= link_to 'destroy', event_comment_path(@event, comment),:method => :delete %>
  </li>
<% end %>
</ul>

    <%= link_to 'new comment', new_event_comment_path(@event) %>

app/views/event_comments/new.html.erb
<%= form_for @comment, :url => event_comments_path(@event) do |f| %>
   <%= f.text_field :comment %>
   <%= f.submit %>
<% end %>

app/views/event_comments/show.html.erb
<p> <%= @comment.comment %> </p>