config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

    resources :orders

    namespace :admin do
      resources :orders
    end

    resources :products do
      member do
        post :buy
        post :cancel
       end
    end
    resources :users

    resources :events do
      resources :comments, :controller => 'event_comments'
      resources :likes
      resources :types, :controller => 'event_types'
    end

      get 'index' => 'abouts#index'
      get 'about' => 'abouts#about'

     root 'abouts#index'

end

app/models/product.rb
class Product < ActiveRecord::Base

  has_many :line_items
  has_many :carts, :through => :line_items

  has_many :line_items
  has_many :orders, :through => :line_items

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController



  def index
    @products = Product.page( params[:id] )
  end

  def show
    @product = Product.find( params[:id])
  end

  def new
    @product = Product.new
  end

  def create
  end


  def create
  end


  def destroy
  end

  def update
  end

  def buy
     @product = Product.find( params[:id] )

      if params[:qty]
        qty = params[:qty].to_i
      else
        qty = 1
      end

      current_cart.add_product( @product, qty )

      respond_to do |format|
        format.html { redirect_to :back }
        format.js # buy.js.erb
      end

   end

   def cancel
     @product = Product.find( params[:id] )
     current_cart.remove_product(@product)

     redirect_to :back
   end

end

app/views/products/_cart.html.erb
<p>Total: <%= current_cart.total %> </p>

<p>Amount:  $<%= current_cart.amount %></p>

<ul>
  <% current_cart.line_items.each do |line| %>
    <li>
      <%= line.product.name %> 買了 <%= line.qty %> 個
      <%= link_to "取消", cancel_product_path( line.product ), :method => :post %>
    </li>
  <% end %>
</ul>

app/views/products/buy.js.erb
$("#cart").html("<%=j render( :partial => "cart") %>");

app/views/products/index.html.erb
<h1>Product List</h1>

<p>
  <%= link_to "結帳!", new_order_path, :class => "btn btn-primary" %>
</p>

<div id="cart">
 <%= render "cart" %>
</div>

<% @products.each do |p| %>


    <div class="item">

      <%= link_to product_path(p) do %>
        <%= p.name %>
      <% end %>


      $<%= p.price %>

    </div>

 <%= button_to "Buy", buy_product_path(p), :class => "btn btn-danger btn-xs", :method => :post, :remote => true  %>

<% end %>

app/views/products/show.html.erb
<div id="cart">
 <%= render "cart" %>
</div>

<h1><%= @product.name %></h1>


<%= form_tag buy_product_path(@product), :remote => true do %>

   <%= select_tag "qty", options_for_select( 1..10 ) %>
   <%= submit_tag "Buy", :class => "btn btn-danger btn-xs" %>

<% end %>

<%= @product.price %>
<%= simple_format @product.description %>