config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

    resources :orders

    namespace :admin do
      resources :orders
    end

    resources :products do
      member do
        post :buy
        post :cancel
       end
    end
    resources :users

    resources :events do
      resources :comments, :controller => 'event_comments'
      resources :likes
      resources :types, :controller => 'event_types'
    end

      get 'index' => 'abouts#index'
      get 'about' => 'abouts#about'

     root 'abouts#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title><%= @page_title || "FZR STUDIO" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="/js/jquery.min.js"></script>
  <script src="/js/jquery.masonry.min.js"></script>
</head>

<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '262683007398393',
      xfbml      : true,
      version    : 'v2.5'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

<div class="container">
<body>

 <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="navbar-brand">
                <%= link_to 'FZR STUDIO', events_path %>
                </div>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <%= link_to '關於本站', about_path %>
                    </li>
                    <li>
                        <%= link_to "所有車種", events_path%>
                    </li>
                    <li>
                        <%= link_to "FZR" , "/events?type_id=1"%>
                    </li>
                    <li>
                        <%= link_to "FZ2" , "/events?type_id=2"%>
                    </li>
                    <li>
                        <%= link_to "FZ1" , "/events?type_id=3"%>
                    </li>
                    <li>
                        <%= link_to '賣場', products_path %>
                    </li>
                    <li>
                       <%= link_to '回到首頁', events_path %>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <div class="login clearfix">
      <% if current_user %>
        Hi!
        <%= link_to current_user.email, user_path(current_user),:method => :get%>
        <%= link_to('登出', destroy_user_session_path, :method => :delete) %> |
        <%= link_to('修改密碼', edit_registration_path(:user)) %>
      <% else %>
        <%= link_to "登入 Facebook", user_omniauth_authorize_path(:facebook) %>
        <%= link_to('註冊', new_registration_path(:user)) %> |
        <%= link_to('登入', new_session_path(:user)) %>
      <% end %>
    </div>

<p style="color: green"><%= flash[:notice] %></p>
<p style="color: red"><%= flash[:alert] %></p>

<%= yield %>

        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>FZR STUDIO &copy; Steven Chen 2016</p>
                </div>
            </div>
        </footer>
</body>
</div>
</html>

app/views/layouts/application.js.erb
$('#events').html('<%= escape_javascript render(@events) %>');
$('#paginator').html('<%= escape_javascript(paginate(@events, :remote => true).to_s) %>');

app/views/layouts/no_header.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title || "FZR STUDIO" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>


</body>

</html>